import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // The Expo app has its own toolchain (mobile/).
    "mobile/**",
    // Generated by the mobile-verify harness (Playwright reports/artifacts) —
    // git-ignored, but lint them too if a local run left them around.
    "mobile-verify/report/**",
    "mobile-verify/.artifacts/**",
    "mobile-verify/screenshots/**",
    "mobile-verify/test-results/**",
    // Vendored third-party agent skills — not app code.
    ".claude/**",
    ".agents/**",
  ]),
]);

export default eslintConfig;
